app/models.py
from flask import current_app
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    users = db.relationship('User', backref='role', lazy='dynamic')

    def __repr__(self):
        return '<Role %r>' % self.name


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=False, index=True)
    password_hash = db.Column(db.String(128))
    roles = db.Column(db.String(64), unique=False, index=True)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))


class Requisitions:
    def __init__(self):
        pass
    __tablename__ = 'Requisition'
    project_id = db.Column(db.Integer, primary_key=True)
    project_name = db.Column(db.String(64), unique=False, index=True)
    client_name = db.Column(db.String(64), unique=True, index=True)
    requested_by = db.Column(db.String(64), unique=False, index=True)
    approved_by = db.Column(db.String(64), unique=True, index=True)
    chargetoAcc = db.Column(db.String(64), unique=False, index=True)
    delivered_to = db.Column(db.String(64), unique=True, index=True)
    duration = db.Column(db.String(64), unique=False, index=True)


    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<User %r>' % self.username

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectMultipleField, PasswordField
from wtforms.validators import InputRequired, Length, Email, Regexp

Accounts = [('Main_acc.', 'General Accounts'), ('Project_acc', 'Project Account'), ('Financial_Office', 'Finances'),
            ('Other', 'Others')]


class NameForm(FlaskForm):
    name = StringField('What is your name?', validators=[InputRequired()])
    submit = SubmitField('Submit')


class RequisitionForm(FlaskForm):
    requested_by = StringField('Requested by', validators=[InputRequired(), Length(1, 64),
                                                           Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
                                                                  'Usernames must have only letters, '
                                                                  'numbers, dots or underscores')])
    approved_by = StringField('Approved by', validators=[InputRequired(), Length(1, 64),
                                                         Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
                                                                'Usernames must have only letters, '
                                                                'numbers, dots or underscores')])
    chargetoAcc = SelectMultipleField('Select role on team', choices=Accounts)

    delivered_to = StringField('Charged to Account', validators=[InputRequired(), Length(1, 64),
                                                                 Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
                                                                        'Usernames must have only letters, '
                                                                        'numbers, dots or underscores')])
    project_name = StringField('Project Name', validators=[InputRequired(), Length(1, 64),
                                                                 Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
                                                                        'Usernames must have only letters, '
                                                                        'numbers, dots or underscores')])
    client_name = StringField('Client Name', validators=[InputRequired(), Length(1, 64),
                                                                 Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
                                                                        'Usernames must have only letters, '
                                                                        'numbers, dots or underscores')])
    budget = StringField('Total Budget', validators=[InputRequired(), Length(1, 64),
                                                                     Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
                                                                            'Usernames must have only letters, '
                                                                            'numbers, dots or underscores')])
    duration = StringField('Duration', validators=[InputRequired(), Length(1, 64),
                                                                     Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
                                                                            'Usernames must have only letters, '
                                                                            'numbers, dots or underscores')])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy
from flask_moment import Moment
from config import config
from flask_login import LoginManager



bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    from main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, redirect, url_for
from ..models import Requisitions
from app import db
from app.main.forms import RequisitionForm
from . import main


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/example')
def mapview():
    return render_template('example.html')


@main.route('/map')
def items():
    return render_template('map.html')


@main.route('/requisition')
def requisition():
    form = RequisitionForm()
    if form.validate_on_submit():
        requisition = Requisitions(project_name=form.project_name.data,
                                   client_name=form.client_name.data,
                                   requested_by=form.requested_by.data,
                                   approved_by=form.approved_by.data,
                                   chargetoAcc=form.chargetoAcc.data,
                                   delivered_to=form.delivered_to.data,
                                   duration=form.duration.data
                                   )
        db.session.add(requisition)
        db.session.commit()
        return redirect(url_for('main.example'))
    return render_template('request_requisition.html', form=form)

app/templates/base.html
{% extends "bootstrap/base.html" %}


{% block title %}GEONET ERP SYSTEM{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">GEONET ERP SYSTEM</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
            </ul>
             <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.items') }}">item</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-xs-12" >
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}

{{ super() }}
{{ moment.include_moment() }}
{%- endblock scripts %}

app/templates/example.html
{% extends "base.html" %}

{% block content %}

    <div class="jumbotron">
      <div class="container">
        <h1 class="display-3">Warehouse</h1>
        <p>Add/Remove new stock items, check stock levels, Approve Project Requisitions.</p>
        <p><a class="btn btn-primary btn-lg" href="{{ url_for('main.requisition') }}" role="button">Fill Requisition form  &raquo;</a></p>
      </div>
    </div>

    <div class="page-header">

        <div class="row">
            <div class="col-md-6">
                <h1>Requisitions</h1>
            </div>
            <div class="col-md-6">
            </div>
        </div>

        <div id="success-alert" class="alert alert-success text-center font-14" style="display: none; margin-bottom: 10px;">
            Request processed successfully
        </div>

        <table style="border: 10px"  class="table">
            <thead>
                <tr>
                    <th>
                        ID
                    </th>
                    <th>
                        Project Name
                    </th>
                    <th>
                        Client Name
                    </th>
                    <th>
                        Budget
                    </th>
                    <th>
                        Duration
                    </th>
                    <th>
                        Start Date
                    </th>
                    <th class="text-center">
                        ACTION
                    </th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td>
                        1
                    </td>
                    <td>
                        ERP Management System
                    </td>
                    <td>
                        Geonet Technologies
                    </td>
                    <td>
                        ¢ 20000.00
                    </td>
                    <td>
                        3 Months
                    </td>
                    <td>
                        10th March, 2018
                    </td>
                    <td class="text-center">
                        <a data-toggle="modal" data-target="#addItemModal" href="#">View details</a>
                    </td>
                </tr>
                <tr>
                    <td>
                        2
                    </td>
                    <td>
                        Website Development
                    </td>
                    <td>
                        Geonet Technologies
                    </td>
                    <td>
                        ¢ 5000.00
                    </td>
                    <td>
                        1 Month

                    </td>
                    <td>
                        10th March, 2018
                    </td>
                    <td class="text-center">
                        <a data-toggle="modal" data-target="#addItemModal" href="#">View details</a>
                    </td>
                </tr>
                <tr>
                    <td>
                        3
                    </td>
                    <td>
                        School Wiring
                    </td>
                    <td>
                        Government
                    </td>
                    <td>
                        ¢ 500000.00
                    </td>
                    <td>
                        12 Months
                    </td>
                    <td>
                        10th March, 2018
                    </td>
                    <td class="text-center">
                        <a data-toggle="modal" data-target="#addItemModal" href="#">View details</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="modal fade" id="addItemModal" tabindex="-1" role="dialog" aria-labelledby="addItemModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" style="color: #000000 !important" class="close"
                        data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <p class="modal-title" style="font-size: 18px;" id="addItemModalLabel">
                    Requisition Details
                </p>
            </div>

            <div class="modal-body">
                <h2>Items Needed</h2>
                <table style="margin-top: 10px" class="table">
                    <thead>
                        <tr>
                            <th>
                                ID
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Category
                            </th>
                            <th>
                                Quantity
                            </th>
                        </tr>
                    </thead>

                    <tbody data-bind="foreach: items">
                        <tr>
                            <td>
                                1
                            </td>
                            <td>
                                HP Envy i7 Laptop
                            </td>
                            <td>
                                Electronics
                            </td>
                            <td>
                                2 pieces
                            </td>
                        </tr>
                        <tr>
                            <td>
                                2
                            </td>
                            <td>
                                Apple MacBook Pro
                            </td>
                            <td>
                                Electronics
                            </td>
                            <td>
                                1 piece
                            </td>
                        </tr>
                        <tr>
                            <td>
                                3
                            </td>
                            <td>
                                Fibre Optic Cable
                            </td>
                            <td>
                                Cables
                            </td>
                            <td>
                                10 cm
                            </td>
                        </tr>
                        <tr>
                            <td>
                                4
                            </td>
                            <td>
                                Co-axial Cable
                            </td>
                            <td>
                                Cables
                            </td>
                            <td>
                                5 cm
                            </td>
                        </tr>
                    </tbody>
                </table>

                <div class="row">
                    <div class="col-md-6">
                        <button id="btn-confirm" style="margin-top: 5px;"
                                type="button"
                                data-dismiss="modal"
                                class="btn btn-primary btn-block">
                            Confirm
                        </button>
                    </div>
                    <div class="col-md-6">
                        <button id="btn-deny" style="margin-top: 5px;"
                                type="button"
                                class="btn btn-outline-danger btn-block">
                            Deny
                        </button>
                    </div>
                </div>

                <div id="reason-form" style="display: none">
                    <textarea style="margin-top: 10px" placeholder="Reason for denying" class="form-control"></textarea>

                    <button id="btn-send-denying-reason" style="margin-top: 5px;"
                            type="button"
                            data-dismiss="modal"
                            class="btn btn-success">
                        SEND
                    </button>

                    <button id="btn-cancel-denying" style="margin-top: 5px;"
                            type="button"
                            class="btn btn-outline-primary">
                        CANCEL
                    </button>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock content %}

{% block scripts %}
    <script type="text/javascript">
    $(document).ready(function () {
        $('#btn-deny').on('click', function () {
            $('#reason-form').fadeIn();
        });

        $('#btn-cancel-denying').on('click', function () {
            $('#reason-form').fadeOut();
        });

        $('#btn-confirm').on('click', function () {
            $('#success-alert').css({
                'display': 'block'
            });
        });

        $('#btn-send-denying-reason').on('click', function () {
            $('#success-alert').css({
                'display': 'block'
            });
        });
    });
    </script>
{% endblock scripts %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}WbAp{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1 class="text-center">
                Welcome to GEONET ERP SYSTEM
        {% if current_user.is_authenticated %}{{ current_user.username }}{% else %}Stranger{% endif %}!</h1>
</div>
<div class="container marketing">

      <div class="row">
        <div class="col-lg-5">
          <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Project</h2>
          <p>Create, update and make requisitions for projects</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Read more</a></p>
        </div><!-- /.col-lg-4 -->
         <div class="col-lg-5">
          <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Warehouse</h2>
          <p>Add/Remove new stock items, check stock levels, Approve Project Requisitions</p>
          <p><a class="btn btn-lg btn-primary" href="{{ url_for('main.mapview') }}" role="button">Read more</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-5">
          <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Finance</h2>
          <p>Budgets, Forecasts, and cashflows</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Read more</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-5">
          <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>HRM</h2>
          <p>Employee, Absence and salary management. Manage your People for sucess</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Read more</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->



{% endblock %}

app/templates/map.html
{% extends "base.html" %}

{% block content %}
    <div>

        <div class="row">
            <div class="col-md-6">
                <h1>Items</h1>
            </div>
            <div class="col-md-6">
                  <button style="margin-top: 5px;"
                        data-bind="click: addItem"
                        type="button"
                        class="btn btn-primary float-right">
                    New Item
                </button>
            </div>
        </div>

        <table style="margin-top: 10px" class="table">
            <thead>
                <tr>
                    <th>
                        ID
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Category
                    </th>
                    <th>
                        Qty Status
                    </th>
                    <th>
                        Item Cost
                    </th>
                    <th>
                        Date Modified
                    </th>
                    <th class="text-center">
                        ACTION
                    </th>
                </tr>
            </thead>

            <tbody data-bind="foreach: items">
                <tr>
                    <td data-bind="text: id">
                    </td>
                    <td data-bind="text: item_name">
                    </td>
                    <td data-bind="text: category.description">
                    </td>
                    <td data-bind="text: quantity_status">
                    </td>
                    <td>
                        ¢ <span data-bind="text: item_cost"></span>
                    </td>
                    <td data-bind="text: date_modified"></td>
                    <td class="text-center">
                        <a data-bind="click: $parent.editItem" href="#">Edit</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

     <!--Modals-->
    <div class="modal fade" id="addItemModal" tabindex="-1" role="dialog" aria-labelledby="addItemModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" style="color: #000000 !important" class="close"
                        data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <p data-bind="text: modalTitle" class="modal-title" style="font-size: 18px;" id="addItemModalLabel">
                </p>
            </div>

            <div class="modal-body">
                <h4 class="text-center" data-bind="text: heading"></h4>
                <div id="message-alert" style="margin-bottom: 10px;" class="text-center alert">
                    <span id="message-alert-text"
                          class="alert-text">
                    </span>
                </div>
{#                <form action="{% url 'warehouse-add-items' %}" method="post">#}
{#                    {% csrf_token %}#}

                    <input type="hidden" id="item_id" name="item_id" value="-1">

                    <div class="form-group">
                        <!--<div class="text-center"><i class="icon-user"></i></div>-->
                        <input id="item_name"
                               type="text"
                               name="item_name"
                               class="form-control"
                               placeholder="Item name"
                               required
                               style="height: 40px; padding-top: 2.5px;">
                    </div>

                    <div class="form-group">
                        <!--<div class="text-center"><i class="icon-user"></i></div>-->
                        <textarea id="description"
                               name="description"
                               class="form-control"
                               placeholder="Description of item"
                               style="height: auto;" maxlength="500" rows="3" cols="1"></textarea>
                    </div>

                    <div class="form-group">
                        <!--<div class="text-center"><i class="icon-gauge"></i></div>-->
                        <input id="total_cost"
                               type="text"
                               name="total_cost"
                               class="form-control"
                               placeholder="Total cost per item e.g. 10.50"
                               required
                               style="height: 40px; padding-top: 2.5px;">
                    </div>
                    <div class="form-group">
                        <select id="category" style="height: auto;"
                                name="category"
                                class="form-control"
                                style="height: 40px; padding-top: 2.5px;" required>
                                <option value="">-- Select category --</option>
                            {% for category in categories %}
                                <option value="{{ category.id }}">{{ category.description }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <select id="quantity_status" style="height: auto;"
                                name="quantity_status"
                                class="form-control"
                                style="height: 40px; padding-top: 2.5px;" required>
                            <option value="">-- Select quantity status --</option>
                            <option value="In Stock">In Stock</option>
                            <option value="Out Of Stock">Out Of Stock</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <button id="btn-save"
                                type="submit"
                                class="btn btn-success btn-block">
                            SAVE
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
{% endblock content %}

{% block scripts %}
    <script type="text/javascript">
    $(document).ready(function () {
        function ItemViewModel () {
            var self = this;
            self.heading = ko.observable('');
            self.modalTitle = ko.observable('');
            self.items = ko.observableArray([]);

            self.loadItems = function() {
                if (self.items().length < 1) {
                    console.log('Get items');
                    $.ajax({
                        url: '/warehouse/ajax/get-items/',
                        type: 'GET',
                        success: function (data) {
                            if (data.success === true) {
                                self.items(data.items);

                                console.log('items retrieved');
                            }
                        },
                        error: function () {
                            // Show an error message
                        }
                    });
                }
            };

            self.loadItems();

            self.addItem = function() {
                self.heading('Add New Item');
                self.modalTitle('New Item');
                $('#message-alert').hide();
                $('#addItemModal').modal('show');

                $('#item_id').val(-1);
                $('.form-control').val('');
            };

            self.editItem = function(item) {
                self.heading('Edit Existing Item');
                self.modalTitle('Edit Item');

                $('#item_id').val(item.id);
                $('#item_name').val(item.item_name);
                $('#description').val(item.description);
                $('#quantity_status').val(item.quantity_status);
                $('#total_cost').val(item.item_cost);
                $('#category').val(item.category.id);

                $('#addItemModal').modal('show');
            };
        }

        ko.applyBindings(new ItemViewModel());
    });
    </script>
{% endblock scripts %}

app/templates/request_requisition.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}GEONET ERP SYSTEM - Register{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Register</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block title %}WbAp{% endblock%}

{% block page_content %}
<div class="page-header">
    <h1>Hello, {{ name }}!</h1>
</div>
{% endblock %}